### ISSUE TITLE
Latest react-native and Node causing dependency issues?

### ISSUE THREAD

**Issue by MattFoley** [darkrishabh/react-native-db-models#10]
I'm getting a rather strange problem with this dependency in the latest React Native. I'm running 0.15-rc of React Native, and I've tried both Node 4 and Node 5. On attempting to package for iOS, I get this error. 

It seems to be coming from the promise-es6 dependency of this project. Has anyone else seen this?

```
Unable to resolve module util from /Users/tfallon/Documents/Code/project/sdk-ota/node_modules/react-native-db-models/node_modules/promise-es6/lib/utils.js: Invalid directory /Users/node_modules/util
    at /Users/tfallon/Documents/Code/project/sdk-ota/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js:323:15
    at tryCallOne (/Users/tfallon/Documents/Code/project-ios/sdk-ota/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/tfallon/Documents/Code/project-ios/sdk-ota/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/tfallon/Documents/Code/project-ios/sdk-ota/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
See logs /var/folders/n8/p633b8_x3bz4cbyz8gz50xhw0000gn/T/react-packager.log
    at SocketClient._handleMessage (/Users/tfallon/Documents/Code/project-ios/sdk-ota/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:131:23)
    at BunserBuf.<anonymous> (/Users/tfallon/Documents/Code/project-ios/sdk-ota/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:52:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/tfallon/Documents/Code/project-ios/sdk-ota/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/tfallon/Documents/Code/project-ios/sdk-ota/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

**Comment by BilalBudhani** [comment]
I'm getting the same error. Did you find a way to resolve it? @MattFoley

**Comment by darkrishabh** [comment]
I will publish the new npm package tomorrow, which will resolve this issue. Did you try installing directly via github url?

**Comment by BilalBudhani** [comment]
@darkrishabh directly installing from github url totally worked. Thanks!

**Comment by Sir-Chasington** [comment]
New npm package available yet?

**Comment by Sir-Chasington** [comment]
If you npm: change a line in node_modules/react-native-db-models/node_modules/promise-es6/lib/utils.js

Line 50 was `require('util').inspect(obj, {`

Change to:  `require('./utils').inspect(obj, {`

Should work after that

**Comment by tmhn** [comment]
@chipe13 Your suggested fix worked, thanks :+1:

**Comment by darkrishabh** [comment]
@chipe13 new npm is available now. Sorry for the delay
